# This is a basic workflow to help you get started with Actions

name: GitHub-Profile-3D-Contrib

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: PrimeEagle/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          IGNORE_LANGUAGES : "Visual Basic.NET,Visual Basic 6.0,VBA,ASP.NET,Smalltalk,Batchfile,XSLT,TSQL,HTML,CSS,ShaderLab,HLSL,Classic ASP,Shell,GLSL,AutoIt"
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
